# Generated by Django 5.0.14 on 2026-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_bid_price_deadline_request_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contractor_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
