# Generated by Django 5.0.14 on 2026-07-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_request_contractor_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='considered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('under_review', 'Рассмотрение исполнителей'), ('awarded', 'В работе'), ('result_submitted', 'Результат сдан'), ('accepted', 'Принято заказчиком')], default='open', max_length=20),
        ),
    ]
