# Generated by Django 5.0.14 on 2026-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_backfill_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_note',
            field=models.TextField(blank=True),
        ),
    ]
