# Generated by Django 5.0.14 on 2026-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='attestation_scan',
            field=models.FileField(blank=True, upload_to='contractor_documents/attestations/'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='license_scan',
            field=models.FileField(blank=True, upload_to='contractor_documents/licenses/'),
        ),
    ]
