# Generated by Django 5.0.14 on 2026-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organization_name_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
