# Generated by Django 5.0.14 on 2026-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contractorprofile_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Документы не загружены'), ('pending', 'На проверке'), ('verified', 'Верифицирован'), ('rejected', 'Отклонён')], default='not_submitted', max_length=20),
        ),
    ]
